#!/usr/bin/env python
"""
Brain parenchyma and intracranial volume per case, as a Slicer segmentation and a CSV.

Two overlapping measurements, written as separate Slicer layers so each can be shown
and measured on its own:

  ICV    the union of every brain_structures label, cut at the foramen magnum - taken
         as the lowest world-Z the `total` task's brain mask reaches, which is where
         that mask stops.

  brain  the `total` task's brain mask MINUS subarachnoid space, ventricles and
         venous sinuses (dural sinuses, falx, tentorium), then clipped to the ICV.
         Parenchyma only, so brain sits inside ICV rather than beside it.

Self-contained: any case missing brain_structures or total/brain is segmented first
by calling segment_structures.py, so a bare folder of DICOMs is enough to start.

    python brain_icv.py --group STUDY
    python brain_icv.py --group STUDY --case CASE_A
    python brain_icv.py --group STUDY --limit 5 --nifti

Writes <case>/brain_icv.seg.nrrd and brain_icv.stats.json into the group's results
folder, plus one brain_icv_volumes_ml.csv for the group.
"""
import argparse
import csv
import json
import re
import traceback

import numpy as np
import nibabel as nib
import nrrd

from segment_fossae import (log, load_bool, world_z, run_task_for_case,
                            discover_cases, BRAIN_TASK)
from ct_dates import study_date
from ct_paths import seg_dir_for

COLORS = {"intracranial_volume": "0.400 0.750 1.000", "brain": "1.000 0.450 0.450"}
# taken out of the brain mask to leave parenchyma: CSF spaces and the dural folds
NOT_PARENCHYMA = ("subarachnoid_space", "ventricle", "venous_sinuses")


def bbox_extent(mask):
    nz = np.argwhere(mask)
    if not len(nz):
        return "0 0 0 0 0 0"
    mn, mx = nz.min(0), nz.max(0)
    return f"{mn[0]} {mx[0]} {mn[1]} {mx[1]} {mn[2]} {mx[2]}"


def write_two_layer_segnrrd(segments, affine, out_path):
    """Each segment on its own layer, so the two may overlap.

    Mirrors the LPS conventions of segment_structures.multilabel_to_segnrrd; a
    multilabel volume cannot represent brain nested inside ICV, hence the layers."""
    lps = affine.copy()
    lps[0, :] *= -1
    lps[1, :] *= -1
    dirs = [lps[:3, 0].tolist(), lps[:3, 1].tolist(), lps[:3, 2].tolist()]
    data = np.stack([m.astype(np.uint8) for _, m in segments], axis=0)
    header = {
        "type": "unsigned char", "dimension": 4,
        "space": "left-posterior-superior",
        "space directions": [[float("nan")] * 3, dirs[0], dirs[1], dirs[2]],
        "kinds": ["list", "domain", "domain", "domain"],
        "space origin": lps[:3, 3].tolist(),
        "encoding": "gzip",
        "Segmentation_MasterRepresentation": "Binary labelmap",
    }
    for i, (name, mask) in enumerate(segments):
        header.update({
            f"Segment{i}_ID": name, f"Segment{i}_Name": name,
            f"Segment{i}_Layer": str(i), f"Segment{i}_LabelValue": "1",
            f"Segment{i}_Color": COLORS.get(name, "0.500 0.800 0.600"),
            f"Segment{i}_Extent": bbox_extent(mask),
            f"Segment{i}_NameAutoGenerated": "0",
            f"Segment{i}_ColorAutoGenerated": "0",
        })
    nrrd.write(str(out_path), data, header, index_order="F")


def ensure_masks(group, case, device, segment=True):
    """Segment whatever this case is missing, so a bare DICOM folder is enough.

    With segment=False the missing pieces are reported instead. Tabulating what has
    already been computed and segmenting a study are both reasonable things to ask
    for, but they take seconds and hours respectively, so the caller says which.
    """
    d = seg_dir_for(group) / case
    bdir, brain_p = d / BRAIN_TASK, d / "total" / "brain.nii.gz"
    if not (bdir.is_dir() and any(bdir.glob("*.nii.gz"))):
        if not segment:
            log(f"{case}: no {BRAIN_TASK} - skipping", 1)
            return bdir, brain_p
        log(f"{case}: no {BRAIN_TASK} - segmenting", 1)
        run_task_for_case(group, case, device, BRAIN_TASK)
    if not brain_p.exists():
        if not segment:
            log(f"{case}: no total/brain - skipping", 1)
            return bdir, brain_p
        log(f"{case}: no total/brain - segmenting", 1)
        run_task_for_case(group, case, device, "total", ("--roi-subset", "brain"))
    return bdir, brain_p


def process_case(group, case, device, write_nifti=False, segment=True):
    d = seg_dir_for(group) / case
    bdir, brain_p = ensure_masks(group, case, device, segment)
    if not brain_p.exists() or not bdir.is_dir():
        return {"case": case, "status": "segmentation unavailable"}

    brain_img = nib.load(str(brain_p))
    affine, shape = brain_img.affine, brain_img.shape
    brain = np.asarray(brain_img.dataobj) > 0
    if not brain.any():
        return {"case": case, "status": "empty brain mask"}

    # ICV = union of every structure label; the parts to subtract are picked out of
    # the same pass so the files are only read once
    icv = np.zeros(shape, bool)
    drop = np.zeros(shape, bool)
    for f in sorted(bdir.glob("*.nii.gz")):
        m = load_bool(f, shape)
        icv |= m
        if f.name[:-7] in NOT_PARENCHYMA:
            drop |= m
    if not icv.any():
        return {"case": case, "status": f"no {BRAIN_TASK} labels"}

    # foramen-magnum floor: the lowest world-Z the brain mask reaches. Computed from
    # the full affine, so an oblique or tilted acquisition is handled.
    wz = world_z(affine, shape)
    min_z = float(wz[brain].min())
    icv &= wz >= (min_z - 1e-3)

    brain_pre = brain & ~drop
    brain_clean = brain_pre & icv          # keep brain nested inside ICV
    vml = float(np.prod(brain_img.header.get_zooms()[:3])) / 1000.0

    d.mkdir(parents=True, exist_ok=True)
    write_two_layer_segnrrd([("intracranial_volume", icv), ("brain", brain_clean)],
                            affine, d / "brain_icv.seg.nrrd")
    if write_nifti:
        nib.save(nib.Nifti1Image(brain_clean.astype(np.uint8), affine),
                 str(d / "brain_icv_brain.nii.gz"))
        nib.save(nib.Nifti1Image(icv.astype(np.uint8), affine),
                 str(d / "brain_icv_icv.nii.gz"))

    stats = {
        "case": case, "status": "ok", "voxel_ml": round(vml, 6),
        "brain_ml": round(int(brain_clean.sum()) * vml, 2),
        "icv_ml": round(int(icv.sum()) * vml, 2),
        "brain_min_worldZ": round(min_z, 2),
        "removed_from_brain_ml": round(int((brain & drop).sum()) * vml, 2),
        "brain_clipped_to_icv_ml": round(int((brain_pre & ~icv).sum()) * vml, 2),
    }
    with open(d / "brain_icv.stats.json", "w") as f:
        json.dump(stats, f, indent=2)
    return stats


def cached_stats(group, case):
    """The numbers from a previous run, when they are still the right ones.

    process_case already writes brain_icv.stats.json per case, and the CSV is those
    numbers in a row - so recomputing them means decompressing seventeen label volumes
    to arrive at what is already on disk. Reused only when the file is newer than every
    input it was made from, so re-running a segmentation invalidates it by itself.
    """
    d = seg_dir_for(group) / case
    f = d / "brain_icv.stats.json"
    if not f.exists():
        return None
    inputs = list((d / BRAIN_TASK).glob("*.nii.gz")) + [d / "total" / "brain.nii.gz"]
    newest = max((i.stat().st_mtime for i in inputs if i.exists()), default=None)
    if newest is None or f.stat().st_mtime < newest:
        return None
    try:
        return json.loads(f.read_text())
    except Exception:
        return None


def natkey(name):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", name)]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--group", default="sample_ct")
    ap.add_argument("--case", nargs="+", default=None)
    ap.add_argument("--limit", type=int, help="only the first N cases")
    ap.add_argument("--device", default="gpu", choices=["gpu", "cpu", "mps"])
    ap.add_argument("--nifti", action="store_true",
                    help="also write the two masks as NIfTI")
    ap.add_argument("--out", default=None)
    ap.add_argument("--recompute", action="store_true",
                    help="ignore each case's saved brain_icv.stats.json and work the "
                         "volumes out again from the masks")
    ap.add_argument("--no-segment", action="store_true",
                    help="tabulate what is already there; report cases that would "
                         "need segmenting rather than segmenting them")
    args = ap.parse_args()

    cases = args.case or sorted(discover_cases(args.group), key=natkey)
    if args.limit:
        cases = cases[:args.limit]

    rows, ok = [], 0
    for i, case in enumerate(cases, 1):
        try:
            s = None if args.recompute else cached_stats(args.group, case)
            if s is not None:
                log(f"[{i}/{len(cases)}] {case}: from {case}/brain_icv.stats.json")
            else:
                s = process_case(args.group, case, args.device, args.nifti,
                                 segment=not args.no_segment)
        except Exception as e:
            s = {"case": case, "status": f"error: {e}"}
            traceback.print_exc()
        s["study_date"] = study_date(args.group, case)[0]
        rows.append(s)
        if s.get("status") == "ok":
            ok += 1
            log(f"[{i}/{len(cases)}] {case}: brain {s['brain_ml']} mL, "
                f"ICV {s['icv_ml']} mL")
        else:
            log(f"[{i}/{len(cases)}] {case}: SKIP - {s['status']}")

    out = args.out or str(seg_dir_for(args.group) / "brain_icv_volumes_ml.csv")
    # The working numbers - the cut height, what was removed, the voxel size - stay in
    # each case's brain_icv.stats.json, where they are there to check a result against.
    # The table is the two volumes.
    cols = ["case", "study_date", "status", "brain_ml", "icv_ml"]
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    log(f"{ok} of {len(cases)} case(s) -> {out}")


if __name__ == "__main__":
    main()
